### ISSUE TITLE
Transparent pixels

### ISSUE THREAD

**Issue by BaerLKR** [0x61nas/aarty#28]
When using aarty on PNGs with a transparent background the program panics because it tried to divide by zero.
```
thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero'
``` 
at line 
```
aarty-0.4.9/src/ascii_processor.rs:18:16
```

**Comment by BaerLKR** [comment]
it only happens in the colored mode

**Comment by BaerLKR** [comment]
when I clone it and run it there it doesn't happen so i guess it was fixed
sry for the unnecessary issue

**Comment by 0x61nas** [comment]
> when I clone it and run it there it doesn't happen so i guess it was fixed sry for the unnecessary issue

actually, the issue is still there but in some way, it doesn't happen all the time even with the same inputs, idk way but this it, but it works most of the time, and this's what's important :D. 'cause if I try to figure out the issue and fix it I'll probably wanna delete all spaghetti that I make in this project and rewrite it, and I don't have a time for this right now
